name: vendor
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  animated_text_kit: ^4.2.2
  animated_widgets: ^1.1.0
  auto_size_text: ^3.0.0-nullsafety.0
  cached_network_image: null
  chewie: null
  connectivity: null
  cupertino_icons: ^1.0.2
  dio: null
  easy_localization: null
  equatable: null
  expandable: ^5.0.1
  firebase_core: null
  firebase_messaging: null
  flutter:
    sdk: flutter
  flutter_barcode_scanner: null
  flutter_bloc: 7.3.3
  flutter_cache_manager: ^3.3.0
  flutter_easyloading: null
  flutter_inappwebview: ^5.4.3+7
  flutter_local_notifications: null
  flutter_localizations:
    sdk: flutter
  flutter_phoenix: ^1.1.0
  flutter_staggered_grid_view: ^0.4.1
  flutter_widget_from_html: null
  fluttertoast: null
  google_fonts: null
  grouped_list: ^5.1.2
  http: null
  image_picker: null
  intl: null
  loading_indicator: null
  loading_overlay_pro: ^2.1.1
  lottie: any
  marquee: ^2.2.3
  math_expressions: null
  modal_bottom_sheet: null
  month_picker_dialog: ^0.4.0
  multi_select_flutter: null
  open_file: 3.2.1
  package_info_plus: null
  page_transition: null
  path_provider: null
  paytm_allinonesdk: null
  permission_handler: null
  provider: null
  pull_to_refresh: null
  qr_code_scanner: null
  share: null
  shared_preferences: null
  sms_autofill: null
  store_redirect: null
  syncfusion_flutter_charts: null
  syncfusion_flutter_datagrid: null
  syncfusion_flutter_datagrid_export: null
  syncfusion_flutter_datepicker: null
  syncfusion_flutter_pdf: null
  syncfusion_flutter_xlsio: null
  timeline_tile: null
  url_launcher: null
  video_player: null
  webview_flutter: null
  youtube_player_iframe: null

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/images/2x/
    - assets/images/3x/
    - assets/locale/
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
